# Site settings
title: Rachel Brindle
description: "Software Engineer and Electric Vehicle enthusiast"
baseurl: ""
url: "https://younata.github.io"
twitter_username: younata
github_username: younata

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

exclude: [vendor, script, Rakefile, Gemfile, Gemfile.lock, README.md]

collections:
  daily:
    output: true
