# Site settings
title: Rachel Brindle
description: "OSX, iOS and Robotics developer"
baseurl: ""
url: "http://younata.github.io"
twitter_username: younata
github_username: younata

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

exclude: [vendor]

collections:
  projects:
    output: true
    permalink: /projects/:path/
